{% set version = "0.11.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-readstata13
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/readstata13_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readstata13/readstata13_{{ version }}.tar.gz
  sha256: 9e6df4bebc775f34262f676d1374060056809e9478bbd8455e3a6d7fc4272d21

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.5
  run:
    - r-base
    - r-rcpp >=0.11.5

test:
  commands:
    - $R -e "library('readstata13')"           # [not win]
    - "\"%R%\" -e \"library('readstata13')\""  # [win]

about:
  home: https://github.com/sjewo/readstata13
  license: GPL-2.0-only
  summary: Function to read and write the 'Stata' file format.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: readstata13
# Type: Package
# Title: Import 'Stata' Data Files
# Version: 0.9.2
# Authors@R: c( person("Jan Marvin", "Garbuszus", email = "jan.garbuszus@ruhr-uni-bochum.de", role = c("aut")), person("Sebastian", "Jeworutzki", email="Sebastian.Jeworutzki@ruhr-uni-bochum.de", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-2671-5253")), person("R Core Team", role="cph"), person("Magnus Thor", "Torfason", role="ctb"), person("Luke M.", "Olson", role="ctb"), person("Giovanni", "Righi", role="ctb"), person("Kevin", "Jin", role="ctb") )
# Description: Function to read and write the 'Stata' file format.
# URL: https://github.com/sjewo/readstata13
# BugReports: https://github.com/sjewo/readstata13/issues
# License: GPL-2 | file LICENSE
# Imports: Rcpp (>= 0.11.5)
# LinkingTo: Rcpp
# ByteCompile: yes
# Suggests: testthat
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2018-05-26 10:41:40 UTC; sj
# Author: Jan Marvin Garbuszus [aut], Sebastian Jeworutzki [aut, cre] (<https://orcid.org/0000-0002-2671-5253>), R Core Team [cph], Magnus Thor Torfason [ctb], Luke M. Olson [ctb], Giovanni Righi [ctb], Kevin Jin [ctb]
# Maintainer: Sebastian Jeworutzki <Sebastian.Jeworutzki@ruhr-uni-bochum.de>
# Repository: CRAN
# Date/Publication: 2018-05-26 22:01:16 UTC
