appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rXD8xzybr0aEF1UVRis88urmB4q2rU+pSm6n2nefbaxRrTn8yq9iRFBNp9AfH2uC+9ut6DpE3bzh4rFs4+XKQDaWULdHBvYrYCCP78ntvRHR7SFt4cjOGcZSm7z7pwTR1zisHMSbJFTbZ//xb7+5CB3dvY2UD/df2TORD2CHzonlmOvHDJ3GpBqoT8/RTSTJxGUv3FVDCyOBbfjZwN1tpd+Y6TT7ThThfmHSsU+Jlz8JYpkltzlQHNjgwH1FHQq+DnP7mZSgUJ9A35RaxlJ3F+DsLSHY4MxxSs0sYoCkp9sbF3UpXmEPfBOYa1LKgHC/hC75/W3zoBXc1VOXhMGY3DI4VQuRx7hU68UA0fmK51neTxH0oLldVt+xQj7poZ88DQ5CS5i2fmxvxMPulPx3l7pw7nB8QvOnW7vsJLwJj3zagqd4kWxsrcCR15vO8TpnFfu8FAkUc/Vi7WTDiE594pRBlZn27LBH51zTPMPrmiRum2lQob4qVAEScsfN+Gy/I1LQzXO41+mE32xSfgqGIxSiKAmRr1NjpHPOeHQBFqJqh1h5lSO8/7ZnZhVmNjyQJQuhmZiOTjRv5acgjWFypSdQogC06+GN4MWu4TI45Gvr71ow4lkIAVJKtIJ43+YNLw+4nmRTuAUg6yKmiB1aj61TN0n0odinpmB7s87dbFw=}
